//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.UserVerificationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserVerificationService.IProformaUserService")]
    public interface IProformaUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaUserService/DoWork", ReplyAction="http://tempuri.org/IProformaUserService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaUserService/DoWork", ReplyAction="http://tempuri.org/IProformaUserService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaUserService/VerifyUser", ReplyAction="http://tempuri.org/IProformaUserService/VerifyUserResponse")]
        string VerifyUser(string EmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProformaUserService/VerifyUser", ReplyAction="http://tempuri.org/IProformaUserService/VerifyUserResponse")]
        System.Threading.Tasks.Task<string> VerifyUserAsync(string EmailAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProformaUserServiceChannel : Proforma.UserVerificationService.IProformaUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProformaUserServiceClient : System.ServiceModel.ClientBase<Proforma.UserVerificationService.IProformaUserService>, Proforma.UserVerificationService.IProformaUserService {
        
        public ProformaUserServiceClient() {
        }
        
        public ProformaUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProformaUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProformaUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProformaUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string VerifyUser(string EmailAddress) {
            return base.Channel.VerifyUser(EmailAddress);
        }
        
        public System.Threading.Tasks.Task<string> VerifyUserAsync(string EmailAddress) {
            return base.Channel.VerifyUserAsync(EmailAddress);
        }
    }
}
