//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Pro_CompanyMeta = new HashSet<CompanyMeta>();
            this.Pro_ProductsCapability = new HashSet<ProductsCapability>();
            this.Pro_ProformaProgram = new HashSet<ProformaProgram>();
            this.Pro_CompanyCategory = new HashSet<CompanyCategory>();
            this.Pro_ProExclusive = new HashSet<ProExclusive>();
        }
    
        public int CompanyId { get; set; }
        public Nullable<int> CategoryId1 { get; set; }
        public string PartnerType { get; set; }
        public string CompanyName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string PrimaryContactFax { get; set; }
        public string Website { get; set; }
        public string FTPSite { get; set; }
        public string ArtEmail { get; set; }
        public string OrderEmail { get; set; }
        public string FOBPointInCanada { get; set; }
        public string QuoteinCanadianDollars { get; set; }
        public string PrimaryContactFirstName { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string PrimaryContactExtension { get; set; }
        public string PrimaryContactDirectLine { get; set; }
        public string SecondaryContactFirstName { get; set; }
        public string SecondaryContactEmail { get; set; }
        public string SecondaryContactExtension { get; set; }
        public string SecondaryContactDirectLine { get; set; }
        public string PrimaryContactTradeOnly { get; set; }
        public string Union { get; set; }
        public string ASI { get; set; }
        public string PPAI { get; set; }
        public string PPPC { get; set; }
        public string SAGE { get; set; }
        public string UPIC { get; set; }
        public string Certifications { get; set; }
        public string MinorityOwned { get; set; }
        public string ProformaPricing { get; set; }
        public string ProformaPrograms { get; set; }
        public string ProductsNCapabilities { get; set; }
        public string Rushor24hour { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string PrimaryContactLastName { get; set; }
        public string PrimaryContactAffiliations { get; set; }
        public string SecondaryContactLastName { get; set; }
        public string SecondaryContactFax { get; set; }
        public string SecondaryContactAffiliations { get; set; }
        public string SecondaryContactTradeOnly { get; set; }
        public string TertiaryContactFirstName { get; set; }
        public string TertiaryContactLastName { get; set; }
        public string TertiaryContactEmail { get; set; }
        public string TertiaryContactDirectLine { get; set; }
        public string TertiaryContactFax { get; set; }
        public string TertiaryContactAffiliations { get; set; }
        public string TertiaryContactTradeOnly { get; set; }
        public string Company_Logo { get; set; }
        public string Status { get; set; }
    
        public virtual Category Pro_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMeta> Pro_CompanyMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsCapability> Pro_ProductsCapability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaProgram> Pro_ProformaProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyCategory> Pro_CompanyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProExclusive> Pro_ProExclusive { get; set; }
    }
}
