//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCategory
    {
        public int CompanyCategoryId { get; set; }
        public int CompanyId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Pro_Category { get; set; }
        public virtual Company Pro_Company { get; set; }
    }
}
