//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMeta
    {
        public int CompanyMetaId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FilterCriteriaId { get; set; }
    
        public virtual Company Pro_Company { get; set; }
        public virtual FilterCriteria Pro_FilterCriteria { get; set; }
    }
}
