//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.Pro_UserNotification = new HashSet<UserNotification>();
        }
    
        public long NotificationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string NotificationType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CretedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotification> Pro_UserNotification { get; set; }
    }
}
