//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaGeneralSettings
    {
        public int ProformaGeneralSettingId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}
