//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Proforma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProformaEntities : DbContext
    {
        public ProformaEntities()
            : base("name=ProformaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyMeta> CompanyMetas { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FilterCriteria> FilterCriterias { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ProductsCapability> ProductsCapabilities { get; set; }
        public virtual DbSet<ProformaGeneralSetting> ProformaGeneralSettings { get; set; }
        public virtual DbSet<ProformaProgram> ProformaPrograms { get; set; }
        public virtual DbSet<SPDevTeam> SPDevTeams { get; set; }
        public virtual DbSet<SPDevTeamMember> SPDevTeamMembers { get; set; }
        public virtual DbSet<SupportCenterContact> SupportCenterContacts { get; set; }
        public virtual DbSet<TermsCondition> TermsConditions { get; set; }
        public virtual DbSet<UserFavorite> UserFavorites { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
