//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportCenterContact
    {
        public long SupportCenterContactId { get; set; }
        public string PrimaryContactNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string LinkedInURL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
