//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public long UserNotificationId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Notification Pro_Notification { get; set; }
    }
}
